<a href="https://colab.research.google.com/github/V1PASH/PYTORCH/blob/main/00_Pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



>  webpage -- https://www.learnpytorch.io/00_pytorch_fundamentals/



In [ ]:
print("helo i m learning py torch")

helo i m learning py torch


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


# introduction to tensors

## creating tensors


tensors are created using torch.tensor

In [ ]:
#scalar

scalar=torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as pyton int
scalar.item()

7

In [ ]:
#vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1][1]

tensor(10)

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR= torch.tensor([[[[1,2,3],
                       [3,6,9],
                       [2,4,5]],
                      [[5,7,3],
                       [3,8,9],
                       [9,4,5]]]])

TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]],

         [[5, 7, 3],
          [3, 8, 9],
          [9, 4, 5]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

In [ ]:
TENSOR[0][1][1][1]

tensor(8)

### Random TENSORS

why random tensors ?

Random tensors are important because of the way many neural network learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

`start with random number-> look at data -> update random number -> look at data`




In [ ]:
### random TENSORS

# size (3,4)

random_tensro=torch.rand(3,4)
random_tensro


tensor([[0.6875, 0.6199, 0.1245, 0.2617],
        [0.6451, 0.8857, 0.2779, 0.1783],
        [0.8642, 0.3718, 0.3428, 0.3886]])

In [ ]:
random_tensro.ndim

2

In [ ]:
#random tensor with similar shape of an image

random_image_size_tensor=torch.rand(size=(3,224,224)) #(height, width , color channel) // can switch too (color channel,height, width )

random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.4332, 0.4090, 0.1779,  ..., 0.6158, 0.3078, 0.4149],
         [0.9361, 0.0558, 0.5663,  ..., 0.1638, 0.2554, 0.2213],
         [0.7221, 0.7858, 0.1066,  ..., 0.2763, 0.6928, 0.2657],
         ...,
         [0.8226, 0.4776, 0.4493,  ..., 0.0129, 0.3654, 0.7525],
         [0.4213, 0.1665, 0.1115,  ..., 0.1797, 0.4960, 0.7414],
         [0.7583, 0.7781, 0.3738,  ..., 0.0160, 0.5955, 0.7677]],

        [[0.3111, 0.2310, 0.7203,  ..., 0.6167, 0.5832, 0.4946],
         [0.4468, 0.2415, 0.7364,  ..., 0.1420, 0.6864, 0.7328],
         [0.0025, 0.6638, 0.8101,  ..., 0.5961, 0.1505, 0.7515],
         ...,
         [0.1441, 0.8139, 0.6829,  ..., 0.2583, 0.6819, 0.9926],
         [0.0975, 0.9859, 0.3242,  ..., 0.9276, 0.2930, 0.4708],
         [0.7382, 0.5267, 0.0736,  ..., 0.1094, 0.1910, 0.3093]],

        [[0.7327, 0.8492, 0.3503,  ..., 0.9112, 0.6851, 0.7264],
         [0.1379, 0.3438, 0.5367,  ..., 0.6774, 0.9352, 0.1805],
         [0.1885, 0.3563, 0.9255,  ..., 0.3923, 0.1270, 0.

##zeros and one tensor

In [ ]:
## zero and ones
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensro

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones= torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

## TENSOR Data types

**Note:** tensor datatypes is one of the 3 big error you will run into with pytorch & learning:

1. Tensors not right dtype
2. Tensors not right shape
3. Tensor not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0,7.0,2.5],
                               dtype=torch.float32,# dtype of tensor
                               device=None, # devie tensor is on
                               requires_grad=False)#track gradient or not
float_32_tensor
float_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.shape

torch.Size([3])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.0000, 7.0000, 2.5000], dtype=torch.float16)

In [ ]:
int_32_tensor=torch.tensor([3.0,7.0,2.5],
                          dtype=torch.int32,
                          requires_grad=False)
int_32_tensor.dtype
int_32_tensor

tensor([3, 7, 2], dtype=torch.int32)

In [ ]:
random_tensor=torch.rand(1,4,3)
random_tensor

tensor([[[0.2938, 0.4059, 0.3062],
         [0.9124, 0.7368, 0.3795],
         [0.9986, 0.0929, 0.9111],
         [0.7859, 0.7236, 0.4138]]])

In [ ]:
random_tensor.shape

torch.Size([1, 4, 3])

In [ ]:
int_64_tensor=int_32_tensor.type(torch.int64)
int_64_tensor

tensor([3, 7, 2])

## operations on tensor


In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9.0000, 49.0000,  6.2500])

In [ ]:
int_32_tensor*int_64_tensor

tensor([ 9, 49,  4])

In [ ]:
int_32_tensor*float_32_tensor

tensor([ 9., 49.,  5.])

In [ ]:
long_32_tensor=int_32_tensor.type(torch.long)
long_32_tensor

tensor([3, 7, 2])

In [ ]:
long_32_tensor*float_32_tensor

tensor([ 9., 49.,  5.])

### Getting info from tensors

1. Tensors not right dtype -- to get dtype form tensor use `tensor.type`
2. Tensor not right shape -- to get shape from tensor use `tensor.shape`
3. Tensor not on the right device -- to get device from tensor use `tensor.device`

In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.5794, 0.3364, 0.2172, 0.6781],
        [0.2552, 0.7542, 0.9899, 0.7631],
        [0.2353, 0.8920, 0.3291, 0.7603]])

In [ ]:
# find out details about some tensor(tensor attributes)

print(some_tensor)

print(f"Datatype of tensor: {some_tensor.dtype}")

print(f"Shape of tensor: {some_tensor.shape}")

print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5794, 0.3364, 0.2172, 0.6781],
        [0.2552, 0.7542, 0.9899, 0.7631],
        [0.2353, 0.8920, 0.3291, 0.7603]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### manipulating tensors

Tensor operations
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [ ]:
# create a tensor

## Addition

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#multiply

tensor*10

tensor([10, 20, 30])

In [ ]:
# subtract
tensor -15

tensor([-14, -13, -12])

In [ ]:
# try out pytorch inbuilt functiom

torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication
Two main ways of performing matrix multiplication

1. Element wise
2. Matrix wise

### @ is used for multiplication in matrix

Ex:- mat1 @ mat2

### We can also use `Torch.matmul(elemenst,elements)`




In [ ]:
## element wise multipliction
print(tensor)
tensor*tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [ ]:
%%time
torch.matmul(tensor,tensor)

#tensor([1, 2, 3])

#1*1 + 2*2+ 3*3

## µs = microseconds

CPU times: user 767 µs, sys: 1.13 ms, total: 1.9 ms
Wall time: 9.22 ms


tensor(14)

In [ ]:
## matrix multiplication by hand

%%time

value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 2.96 ms, sys: 0 ns, total: 2.96 ms
Wall time: 4.43 ms


#### there are two main rules performing matrix multiplication
1. the inner dimension must match

* `(3,2) @ (3,2)` Wont work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work

2.  The result matrix has shape of the **outer Dimensions**
* `(2 , 3) @ (3 , 2)` -> `(2 , 2)`


In [ ]:
# Matrix Wise multiplication

mat1=torch.rand(4,2)
mat2=torch.rand(2,3)

mat1 @ mat2

tensor([[0.5156, 0.5357, 0.7871],
        [0.2203, 0.2213, 0.4332],
        [0.5313, 0.5552, 0.7700],
        [0.3450, 0.3724, 0.3475]])

In [ ]:
torch.matmul(mat1,mat2)

tensor([[0.5156, 0.5357, 0.7871],
        [0.2203, 0.2213, 0.4332],
        [0.5313, 0.5552, 0.7700],
        [0.3450, 0.3724, 0.3475]])

In [ ]:
## randint for tensor with int values at random
%%time
mat1=torch.randint(10,(3,8))
mat2=torch.randint(10,(8,3))

mat1 @ mat2

CPU times: user 281 µs, sys: 0 ns, total: 281 µs
Wall time: 286 µs


tensor([[247, 198, 193],
        [182, 140, 118],
        [194, 155, 128]])

In [ ]:
%%time
torch.matmul(mat1,mat2)

CPU times: user 67 µs, sys: 11 µs, total: 78 µs
Wall time: 82.3 µs


tensor([[247, 198, 193],
        [182, 140, 118],
        [194, 155, 128]])

#### Most common error in deep learning: shape error

In [ ]:
# shapes of matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

In [ ]:
torch.mm(tensor_A,tensor_B)# torch.mm is same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

##### Transpose

To fix our tensor shape issue we can manipulate the shape of onr of our tensors using transpose

A **transpose** chaneges rows to columns and colums to rows

In [ ]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
## tensor.T for transpose (  tensor will be name of the tensor ( .T ) for transpose )
tensor_B.T


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:

torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min , max , mean , sum ,etc(tensor aggeration)


In [ ]:
#create a tensor
x=torch.randint(100 ,(1,10))

# randint( limit of random numbers to choose from ex - 0-100 , (rows,colums))

x

tensor([[21, 63, 81, 60, 93, 36, 45, 78, 71, 66]])

In [ ]:
# max
torch.max(x), x.max()

(tensor(93), tensor(93))

In [ ]:
# min
torch.min(x) , x.min()

(tensor(21), tensor(21))

In [ ]:
# sum
torch.sum(x) ,x.sum()

(tensor(614), tensor(614))

In [ ]:
# Mean

# Note -- the torch.mean require the dtype to be float or complex only to work

torch.mean(x.type(torch.float32))

## type to change dtype


tensor(61.4000)

In [ ]:
x.type(torch.float).mean()

tensor(61.4000)

#### Finding the position of min and max element

In [ ]:
# argmin() -- find the position of tensor that has the minimun value and return the index
torch.argmin(x)

tensor(0)

In [ ]:
# argmax() -- find the position of tensor that has the maximum value and return the index

torch.argmax(x)

tensor(4)

In [ ]:
x [0][9]

tensor(66)

## Rehaping ,Stacking, Squeezing & unsqeezing tensors

* Reshaping -- Reshapes an input into a defined shape
* view  - return a view of an input tensor of a certain shape but Keeps the same memory
* stacking - combine multiple tensors on top of each other
* Squeeze - Remove all `1` dimension from a tensor

* unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# lets create a tesnor

import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape=x.reshape(1,9)
# change the shape first  rows second colums the number of shapes need to equal to number of elements
# ex (3,3)=3*3=9    , number of elements in tensor =
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view

z= x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing Z changes x (cause a view of a tensotr shares the same memorhy as the original)

z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of sach other

x_stack=torch.stack([x,x,x,x],dim=1) #dim = 0 horizontal 1 = vertical
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:

x_reshape

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshape.shape

torch.Size([1, 9])

In [ ]:
x_reshape.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshape.squeeze().shape

torch.Size([9])

In [ ]:
# torch.squeeze
print(f"previous tensor{x_reshape}")
print(f"previous tensor{x_reshape.shape}")


# after squeeze
x_squeeze=x_reshape.squeeze()
print(f"previous tensor{x_reshape.squeeze()}")
print(f"previous tensor{x_reshape.squeeze().shape}")


previous tensortensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous tensortorch.Size([1, 9])
previous tensortensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous tensortorch.Size([9])


In [ ]:
# torch.unsqueeze  -- Add Single dimension at speciic dim

print(f"previous target{x_squeeze}")
print(f"previous tensor{x_squeeze.shape}")
# after squeeze
x_unsqueeze=x_squeeze.unsqueeze(dim=0)

print(f"previous tensor{x_unsqueeze}")
print(f"previous tensor{x_unsqueeze.shape}")


previous targettensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous tensortorch.Size([9])
previous tensortensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous tensortorch.Size([1, 9])


In [ ]:
# torch.permute -- Rearrage the dimension of a target tensor in a specified order

x_original=torch.rand(224,224,3) # height , width , color channel

# permute the original tensor

x_permuted=x_original.permute(2,0,1) # shift axis 0->1, 1->2, 2->0

In [ ]:
x_permuted

tensor([[[0.4008, 0.3334, 0.2544,  ..., 0.1547, 0.3740, 0.8705],
         [0.7355, 0.9207, 0.4009,  ..., 0.2937, 0.6790, 0.2083],
         [0.3418, 0.5748, 0.5851,  ..., 0.9190, 0.8507, 0.1407],
         ...,
         [0.5790, 0.5180, 0.5523,  ..., 0.4178, 0.0577, 0.9642],
         [0.9489, 0.1427, 0.7509,  ..., 0.2976, 0.7035, 0.4050],
         [0.5261, 0.6760, 0.5457,  ..., 0.5715, 0.9082, 0.9048]],

        [[0.5238, 0.7382, 0.9355,  ..., 0.9563, 0.7095, 0.6318],
         [0.5923, 0.1820, 0.5382,  ..., 0.8184, 0.7644, 0.3482],
         [0.9741, 0.1279, 0.1368,  ..., 0.6518, 0.6239, 0.8944],
         ...,
         [0.9732, 0.9482, 0.7412,  ..., 0.5433, 0.8048, 0.4971],
         [0.2530, 0.9165, 0.7056,  ..., 0.9466, 0.8364, 0.6043],
         [0.0432, 0.7427, 0.2332,  ..., 0.1261, 0.5098, 0.8093]],

        [[0.9999, 0.6307, 0.8170,  ..., 0.5713, 0.9219, 0.3274],
         [0.8080, 0.8961, 0.9431,  ..., 0.6032, 0.1540, 0.7732],
         [0.8530, 0.0433, 0.5670,  ..., 0.5210, 0.5508, 0.

In [ ]:
print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]=1

In [ ]:
x_permuted[0,0,0],x_original[0,0,0]

(tensor(1.), tensor(1.))

## Indexing

Indexing with pytorch is similar to indexing with numpy

In [ ]:
x= torch.arange(1,28).reshape(1,3,3,3)
x,
x.shape

torch.Size([1, 3, 3, 3])

In [ ]:
x[0]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [ ]:
x[0][1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [ ]:
x[0][1][1]

tensor([13, 14, 15])

In [ ]:
x[0][1][1][0]

tensor(13)

In [ ]:
# we can also use ":" to select all of the targeted dimension

x[:,1,0]

tensor([[10, 11, 12]])

In [ ]:
x[:,:,1]

tensor([[[ 4,  5,  6],
         [13, 14, 15],
         [22, 23, 24]]])

In [ ]:
# get all vlaue of 0 dimension idex only of 1,2

x[:,:,:,1]

tensor([[[ 2,  5,  8],
         [11, 14, 17],
         [20, 23, 26]]])

In [ ]:
x[:,0,2,2]

tensor([9])

## Pytorch tensors & numpy

Numpy is a popular scientific python numerical computing library
and because of this pytorch has functionality to interact with it

* Data in numpy , want in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# numpy array to tensor

import torch
import numpy as np

array =np.arange(1.,15.,2)
tensor=torch.from_numpy(array) #when converting to tensor  it will convert to default float64 according to numpy not float32
#tensor=torch.from_numpy(array).type(torch.float32

array,tensor

(array([ 1.,  3.,  5.,  7.,  9., 11., 13.]),
 tensor([ 1.,  3.,  5.,  7.,  9., 11., 13.]))

In [ ]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
torch.arange(1.,15.,2).dtype

torch.float32

In [ ]:
array=array+1
# tensor is on new memoryy location
array,tensor

(array([ 3.,  5.,  7.,  9., 11., 13., 15.]),
 tensor([ 1.,  3.,  5.,  7.,  9., 11., 13.]))

In [ ]:
## tensor to numpy array

tensor =torch.randint(10,(1,3))
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([[1, 0, 8]]), array([[1, 0, 8]]))

In [ ]:
tensor.dtype,numpy_tensor.dtype

(torch.int64, dtype('int64'))

In [ ]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([[2, 1, 9]]), array([[1, 0, 8]]))

## Reproducibilty ( trying to take random out of random)

In short how a neural network learn

` start with random number-> tensor operations-> update random numbers to tey and make of the data -> again-> again-> again`

To reduce the randomness in neural network and pytorch  comes concept of **random seed**

Essentially what random seed does is flavour randomness

In [ ]:
torch.rand(3,5,3)

tensor([[[0.6346, 0.7488, 0.6710],
         [0.4343, 0.6563, 0.2630],
         [0.3096, 0.3000, 0.3454],
         [0.7558, 0.8756, 0.1956],
         [0.8177, 0.6797, 0.3812]],

        [[0.6671, 0.2979, 0.7843],
         [0.2264, 0.6107, 0.0948],
         [0.6937, 0.9475, 0.0063],
         [0.0392, 0.2218, 0.7012],
         [0.7955, 0.9001, 0.5861]],

        [[0.9929, 0.3060, 0.5594],
         [0.0613, 0.4907, 0.9416],
         [0.8435, 0.0085, 0.1823],
         [0.4088, 0.5534, 0.0412],
         [0.6819, 0.0071, 0.0278]]])

In [ ]:
import torch

# create two random tensors

random_tensor_A=torch.rand(5,3)
random_tensor_B=torch.rand(5,3)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)

tensor([[0.9240, 0.3136, 0.9903],
        [0.7219, 0.1097, 0.6238],
        [0.3392, 0.7721, 0.5619],
        [0.1126, 0.7459, 0.1007],
        [0.1431, 0.3816, 0.7663]])
tensor([[0.5298, 0.1218, 0.0226],
        [0.5620, 0.4505, 0.9981],
        [0.8474, 0.4327, 0.3821],
        [0.1701, 0.8530, 0.8384],
        [0.5529, 0.8645, 0.9077]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
#lets make some random but reproducable tensors

Random_seed=500

torch.manual_seed(Random_seed)
random_tensor_C=torch.rand(5,3)

torch.manual_seed(Random_seed)
random_tensor_D=torch.rand(5,3)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C==random_tensor_D)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105],
        [0.1575, 0.6983, 0.7883],
        [0.7981, 0.4593, 0.8997],
        [0.2518, 0.5648, 0.0302]])
tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105],
        [0.1575, 0.6983, 0.7883],
        [0.7981, 0.4593, 0.8997],
        [0.2518, 0.5648, 0.0302]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


## Running tensors and pytorch objects on GPU

GPU = faster computation on numbers thanks to cuda + nvidia hardware + pytorch working behind the scenes to make everything hunky dory(good)

#### 1. Getting a GPU

1. using gogle colab  (free)
2. use your own GPU (own GPU)
3. Use cloud computing (Paid)


In [ ]:
!nvidia-smi

Wed Sep 25 17:00:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Cheak for GPU access for Pytorch

In [ ]:
# cheak GPU access with pytorch

import torch
torch.cuda.is_available()

True

For pytorch since it able to comptute on both cpu and gpu its best to use device agnostic

eg - use GPU if availble else CPU

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count the number of GPU
torch.cuda.device_count()

1

### 3. Putting tensors and models on the GPU

the reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [ ]:
# crete a tensor defaut device is on cpu
tensor = torch.arange(7,50,2)

tensor,tensor.device

(tensor([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
         43, 45, 47, 49]),
 device(type='cpu'))

In [ ]:
# move tensor to GPU

tensor_gpu=tensor.to(device)
tensor_gpu

#cuda is the gpu 0 is index as we only have one if multiple works with index

tensor([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
        43, 45, 47, 49], device='cuda:0')

#### 4. moving tensor back to CPU

In [ ]:
cpu_tensor=tensor.to("cpu")
cpu_tensor.device

device(type='cpu')

In [ ]:
# if tensor is on GPU cant work with numpy

tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# to fix the gpu tensor with numpy we can take back to cpu

tensor_cpu=tensor_gpu.cpu().numpy()
tensor_cpu

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39,
       41, 43, 45, 47, 49])

In [ ]:
tensor_gpu

tensor([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41,
        43, 45, 47, 49], device='cuda:0')

In [ ]:
## Exercise and extra Curriculam